version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - "libmariadb3"
    - "libmariadb-dev"

sphinx:
  fail_on_warning: True

python:
  install:
    - method: pip
      path: .
