version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - "libmariadb3"
    - "libmariadb-dev"

sphinx:
  fail_on_warning: True
  configuration: "docs/source/conf.py"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
        - API
        - SPF
        - dev
