"""adds SPF and Greylisting per-domain options

Revision ID: 2033b6fde7ed
Revises: ce81767cec26
Create Date: 2022-06-17 14:17:02.723784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2033b6fde7ed"
down_revision = "ce81767cec26"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domains",
        sa.Column("greylist", sa.Boolean(name="greylist"), nullable=True),
    )
    op.add_column(
        "domains",
        sa.Column("check_spf", sa.Boolean(name="check_spf"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domains", "check_spf")
    op.drop_column("domains", "greylist")
    # ### end Alembic commands ###
